name: kanbanboard
version: 1.0.0+1
publish_to: none
description: kanban board
environment: 
  sdk: ^3.5.1

dependencies: 
  cupertino_icons: ^1.0.8
  get: 4.6.6
  http: 1.2.2
  shared_preferences: 2.3.2
  sizer: 3.0.3
  google_fonts: 6.2.1
  uuid: ^4.5.0
  intl: ^0.19.0
  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.0
  firebase_analytics: ^11.3.0
  permission_handler: ^11.3.1
  flutter: 
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

