// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP32TQDffsztOVrJMyGVFb9FUOxvSI6EQ',
    appId: '1:765520173528:web:85a09dc9df9fdc39f03aad',
    messagingSenderId: '765520173528',
    projectId: 'kanban-board-63cbf',
    authDomain: 'kanban-board-63cbf.firebaseapp.com',
    storageBucket: 'kanban-board-63cbf.appspot.com',
    measurementId: 'G-4GBF69N7T6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS13dmrXukjOoeK09rW3NTVH0Uj-_Urug',
    appId: '1:765520173528:android:5c1855b09e093388f03aad',
    messagingSenderId: '765520173528',
    projectId: 'kanban-board-63cbf',
    storageBucket: 'kanban-board-63cbf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBameWcsirW1lY7IN6tSHH3bj3dCWn4gaM',
    appId: '1:765520173528:ios:5192bdda6a448acdf03aad',
    messagingSenderId: '765520173528',
    projectId: 'kanban-board-63cbf',
    storageBucket: 'kanban-board-63cbf.appspot.com',
    iosBundleId: 'com.example.kanbanboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBameWcsirW1lY7IN6tSHH3bj3dCWn4gaM',
    appId: '1:765520173528:ios:5192bdda6a448acdf03aad',
    messagingSenderId: '765520173528',
    projectId: 'kanban-board-63cbf',
    storageBucket: 'kanban-board-63cbf.appspot.com',
    iosBundleId: 'com.example.kanbanboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCP32TQDffsztOVrJMyGVFb9FUOxvSI6EQ',
    appId: '1:765520173528:web:a374eeae6e8c1712f03aad',
    messagingSenderId: '765520173528',
    projectId: 'kanban-board-63cbf',
    authDomain: 'kanban-board-63cbf.firebaseapp.com',
    storageBucket: 'kanban-board-63cbf.appspot.com',
    measurementId: 'G-5M0JK46K2Y',
  );
}
